version: "3.4"

services:
  math_service:
    image: math_service
    build:
      context: back
      dockerfile: ./Dockerfile
    ports:
      - 4002:8080
    networks:
      - network1
    develop:
      watch:
        - action: rebuild
          path: ./back
    # volumes:
    #   - goCacheAuth:/go/pkg/mod
    #   - goCacheAuth:/root/.cache/go-build

# volumes:
# goCacheAuth:

networks:
  network1:
    driver: bridge
